// Pattern B — Enhanced with defaults
export { default as TrxAutoComplete } from './TrxAutoComplete.vue'
export { default as TrxDatePicker } from './TrxDatePicker.vue'
export { default as TrxInputNumber } from './TrxInputNumber.vue'
export { default as TrxPassword } from './TrxPassword.vue'
export { default as TrxSelect } from './TrxSelect.vue'
export { default as TrxMultiSelect } from './TrxMultiSelect.vue'
export { default as TrxListbox } from './TrxListbox.vue'

// Pattern A — Pass-through
export { default as TrxCascadeSelect } from './TrxCascadeSelect.vue'
export { default as TrxCheckbox } from './TrxCheckbox.vue'
export { default as TrxCheckboxGroup } from './TrxCheckboxGroup.vue'
export { default as TrxColorPicker } from './TrxColorPicker.vue'
export { default as TrxFloatLabel } from './TrxFloatLabel.vue'
export { default as TrxFluid } from './TrxFluid.vue'
export { default as TrxIconField } from './TrxIconField.vue'
export { default as TrxIftaLabel } from './TrxIftaLabel.vue'
export { default as TrxInputChips } from './TrxInputChips.vue'
export { default as TrxInputGroup } from './TrxInputGroup.vue'
export { default as TrxInputGroupAddon } from './TrxInputGroupAddon.vue'
export { default as TrxInputIcon } from './TrxInputIcon.vue'
export { default as TrxInputMask } from './TrxInputMask.vue'
export { default as TrxInputOtp } from './TrxInputOtp.vue'
export { default as TrxInputText } from './TrxInputText.vue'
export { default as TrxKnob } from './TrxKnob.vue'
export { default as TrxRadioButton } from './TrxRadioButton.vue'
export { default as TrxRadioButtonGroup } from './TrxRadioButtonGroup.vue'
export { default as TrxRating } from './TrxRating.vue'
export { default as TrxSelectButton } from './TrxSelectButton.vue'
export { default as TrxSlider } from './TrxSlider.vue'
export { default as TrxTextarea } from './TrxTextarea.vue'
export { default as TrxToggleButton } from './TrxToggleButton.vue'
export { default as TrxToggleSwitch } from './TrxToggleSwitch.vue'
export { default as TrxTreeSelect } from './TrxTreeSelect.vue'

// Legacy aliases
export { default as TrxDropdown } from './TrxSelect.vue'
export { default as TrxChips } from './TrxInputChips.vue'
export { default as TrxInputSwitch } from './TrxToggleSwitch.vue'
export { default as TrxCalendar } from './TrxDatePicker.vue'
